### ISSUE TITLE
Fall Damage

### ISSUE THREAD

**Issue by Zarii68** [RatzzFatzz/Minecraft-Fly-Mod#16]
Whenever flying is toggled off, I take falling damage, regardless of how close to the ground I am. For example, today I was building at Y: 140+, flew down to Y: 74 (ground level), toggled off flight and promptly died due to "Fell from a high place". Playing in Minecraft 1.18, but was able to repeat the result in earlier versions. Playing on a server that has cheats and flying enabled.

**Comment by RatzzFatzz** [comment]
Which mod version are  you using?
Can you reproduce the error in single player? Or does it only happen in multiplayer?

**Comment by RatzzFatzz** [comment]
I can't reproduce your finding. Feel free to reopen this issue if you continue to have the problem and can provide more information.
