### ISSUE TITLE
Sprinting does not increase exhaustion level

### ISSUE THREAD

**Issue by TheMingo888** [RatzzFatzz/Minecraft-Fly-Mod#17]
Minecraft Version: 1.18.2
Mod Version: 1.7.2

When sprinting with the mod installed, the exhaustion level does not increase. It should increase 0.1 per meter sprinted, as per the wiki. This is easiest to see with AppleSkin installed so the exhaustion level is visible in the background of the hunger bar. I have manually set the sprinting multiplier to 1.3 so it is identical to regular Minecraft.

**Comment by RatzzFatzz** [comment]
I added an option to toggle exhaustion in v1.8
