### ISSUE TITLE
Don't include Sponge Mixin!

### ISSUE THREAD

**Issue by Fourmisain** [RatzzFatzz/Minecraft-Fly-Mod#8]
Just a heads-up, I wanted to give this mod a try and it failed _spectacularly_ because it contains an old Sponge Mixin version which seemed to cause a conflict with every single other mod.

Fabric Loader already comes with Sponge Mixin, so the fix is to simply delete the `include`:
https://github.com/RatzzFatzz/Minecraft-Fly-Mod/blob/0965e59dbc50be307c5159c1e608a821d8725d93/build.gradle#L46

The mod probably also shouldn't include Fabric API and Cloth Config.
Cloth Config because it's using a very old version (4.8.3 vs the up-to-date 4.11.19) which may cause other mods to use it as well and cause issues.
You can instead add e.g. `"cloth-config2": ">=4.8.0"` to the fabric.mod.json `depends` section and add it to the requirements on your CurseForge page.
Also, Mod Menu should be in neither of those, since you can still use the mod without Mod Menu by editing the `flymod.json` config file.

The Fabric API bundled in the mod jar (under the `META-INF\jars\` directory) is actually empty; it only contains some meta-data, no actual class files, which will fool the loader into thinking Fabric API is installed when it is in fact not, therefore it should be removed as well.
Anyone using any mods is very likely to have Fabric API installed already, so there should really be no reason for trying to include it.

There's so much more I could comment on, but these are the most important things.

**Comment by RatzzFatzz** [comment]
Thanks for telling me. I've more active the last few days in improving the mod and just publish an important bug fix.
I'll look into your suggestions and will update it in the following days. Any feedback is more than welcome.

**Comment by RatzzFatzz** [comment]
I just released a new version with all your findings updated
